apiVersion: v1
kind: Service
metadata:
  name: svc-lb
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: python-deployment
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 8000